export enum SourceProvider {
    WEB_BROWSER = 'WEB_BROWSER',
    MOBILE_BROWSER = 'MOBILE_BROWSER',
    GOOGLE_PLUS = 'GOOGLE_PLUS',
    GOOGLE_ONE_TAP_LOGIN = 'GOOGLE_ONE_TAP_LOGIN',
    FACEBOOK = 'FACEBOOK',
}
